# Trusty Beta requires sudo per https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

services:
  - docker

# We don't actually use anything java, but this feels the least jarring "language"
language: java

# Even though this shouldn't be needed, one build failed because of SSH known hosts:
# https://travis-ci.org/openzipkin/docker-zipkin/builds/78704161
addons:
  ssh_known_hosts: github.com

# Version tags are used to trigger these Travis CI runs
branches:
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

# jq is used in release.sh to parse the responses of the quay.io API
install:
  - sudo wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq
  - sudo chmod o+x /usr/local/bin/jq

before_script:
  # Log in to Docker Hub, needed to mirror images built on quay.io
  - docker login -u dockerzipkindeployer -p "$DOCKERHUB_PASSWORD"

script:
 # Also known as doit.sh
 - ./release.sh $TRAVIS_TAG

env:
  global:
    # The release process syncs minor and major version tags to the newly built subminor version tag
    # via the quay.io API, using these credentials.
    # travis encrypt QUAYIO_OAUTH2_TOKEN=from https://quay.io/organization/openzipkin?tab=applications
    - secure: "Ds/IscOuG6cXRpsiNHjtcylIiJfykaQ+o2Jt1jrcPwvaxYsh1uRS0RVwEUo9JC3Fgchdp1XcoXvylSNcEb8myu7diPZdBicQ5qeduQIb5kKs5ooGB+Z2KfcLIpXZd09yB9Unr7ySnk0djSnG4ZqmXh/SEtrl9bkADCKAYCji44hO2daBR7d0S5hNsBChLAQFgC0BN/uuOOUUGfVL1gYuPojn+MYyJjyTb1D/ddvpHg/a0W5vPpq++sQVo7TObn82AlEFj2Hs2puOx+fMHUTW7HGLbT0LFD8MDeI/sCBdPX/GXOgT5rvoparOmV4af6MLCNz/t1QT/xEFP4jpaJwE68I+hJi5/zZTJcCLev8Th8WoW8kvxMBwgpm4N+CHxsoJjgo9TPyWVNBrhTDwQmA3cRSPpQavUcAJYjhRFQy9onMhgi8+1MOUC1uHadNkGA4UaGQjiLKy0VwLPNHvqtU0JohPM85GAKJtSFVcL4hDNV+s0BexlRhoxj6WDAMaApNScK/tio9rP56yci8QU1osFdV1EVv9da6K/26GXqS97gm6/bcLgJdH2k5Ds9EWKsPwfNzLe/M77VSyIs30fB9hLmnSb2sMXVd2RC6UVRkiuvKbmtHx+IPQbAtQrd0cvfezTkQvp7vyU4ZaN0HC5Un+oDqP8iA5OxhI/PsocQqAsqY="
    # The release process pushes images to Docker Hub, using these credentials
    # travis encrypt DOCKERHUB_PASSWORD=dockerzipkindeployer password from lastpass
    - secure: "E1fq8mUi7FXCr1zLZCLgG4wXEZlVabTN85QQ+8FXo+Jljj6t1Xjsne6pumUHCx60ZApI9t6Oo2taQn57n1NPU6mY5HzEHY4YNMxGO2Mph92QEyipZ7jpy2fuPEJkroCfNghp7mU6cBSXpXf48enggpTv1y8jBa012BWCTLKuDMSaGFn6Ti3EulkLCBrwat5lo4A/kxmLFbmEAJEenxl8V0TGfGB68p5ZdW4LTaGCOTwiXDYrb0eI4w4Yf8DWV/cCskm1SU3hPLst+BBqG/LkrIwpAFJgQy8o68hYi4915yhmk4XrQ6Ld2c3XBe8AFo8oHb5dyz7Oo2cgpydVql5pSiNarh+Z0z19LBRKFT3FkvmV4Gr/kKCv81w6WVMTvHSQZDDE6vNjv5zD8lS0OktWW6dVqiJ8sXBuUEJg8ngOix24h3ttPWnRGs7mvCmaZSGLbdRT9kk0G3UnV/EF1qO9xoIfz/VFJHg5xh5tcjJYv1Nzi9RomlRG4U27Y7LkxftISx7J0/zsYeNfu0nrQBM9Oj7T+zNuxlIV1IuqFJkBs+xzQZyPbC3kpgdNPArPpwfP8I54zo1E59G/W93366+dkIV7RGZiawqf8s8fWI4qOdbd8l2Acgw2XLpYubNLMj5aeCTYk5d1YUuX7OJkQUSbkC1S53hnSAYH7az/OkY7PCE="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false
